language: node_js
node_js:
  - "10.10.0"
cache:
  directories:
    "node_modules"

before_script:
  - npm run build

script:
  - npm run test:converage

after_script: "cat ./coverage/lcov.info | coveralls"
